if HaveItemBool(144) then goto label0 end;
if HaveItemBool(145) then goto label0 end;
if HaveItemBool(146) then goto label0 end;
if HaveItemBool(147) then goto label0 end;
if HaveItemBool(148) then goto label0 end;
if HaveItemBool(149) then goto label0 end;
if HaveItemBool(150) then goto label0 end;
if HaveItemBool(151) then goto label0 end;
if HaveItemBool(152) then goto label0 end;
if HaveItemBool(153) then goto label0 end;
if HaveItemBool(154) then goto label0 end;
if HaveItemBool(155) then goto label0 end;
if HaveItemBool(156) then goto label0 end;
if HaveItemBool(157) then goto label0 end;
Talk("袁某在島上居住這些年來，你是第一個找到這的．", 54, 0);
exit();
::label0::
Talk("袁某在島上居住這些年來，你是第一個找到這的．", 54, 0);
Talk("先生怎么會一個人住在島上？", 0, 0);
Talk("我在這里等你啊．", 54, 0);
Talk("等我？", 0, 0);
Talk("你不是在尋找天書嗎．", 54, 0);
Talk("你．．．你怎么知道？", 0, 0);
Talk("你包里的書都露出來了．", 54, 0);
Talk("＜汗，眼睛真尖＞這么說你跟其中的一本有關？", 0, 0);
Talk("不錯．”碧血劍”一書就在我手里．", 54, 0);
Talk("那怎樣才能給我？", 0, 0);
Talk("只要你能連勝我十場．", 54, 0);
Talk("十場！？", 0, 0);
Talk("準備好時再找我．", 54, 0);
ModifyEvent(-2, -2, -2, -2, 394, 0, 0, -2, -2, -2, 0, -2, -2);