if HaveItemBool(144) == false then goto label0 end;
if HaveItemBool(145) == false then goto label0 end;
if HaveItemBool(146) == false then goto label0 end;
if HaveItemBool(147) == false then goto label0 end;
if HaveItemBool(148) == false then goto label0 end;
if HaveItemBool(149) == false then goto label0 end;
if HaveItemBool(150) == false then goto label0 end;
if HaveItemBool(151) == false then goto label0 end;
if HaveItemBool(152) == false then goto label0 end;
if HaveItemBool(153) == false then goto label0 end;
if HaveItemBool(154) == false then goto label0 end;
if HaveItemBool(155) == false then goto label0 end;
if HaveItemBool(156) == false then goto label0 end;
if HaveItemBool(157) == false then goto label0 end;
Talk("小伙子，不錯啊，這么快就集齊了十四本天書，我之前答應過你，只要集齊天書就為你開啟院子里的門．", 193, 0);
DarkScene();
ModifyEvent(-2, -2, 0, -2, 0, 0, 0, 0, 0, 0, 0, -2, -2);
ModifyEvent(-2, 13, 0, -2, 0, 0, 1141, 0, 0, 0, 0, -2, -2);
LightScene();
exit();
::label0::
Talk("飛雪連天射白鹿笑書神俠倚碧鴛", 193, 0);