AddMorality(1);
Talk("咳、咳．", 69, 1);
Talk("老前輩，你怎么樣？", 0, 0);
Talk("都怪我手下留情，被歐陽鋒偷襲成功．咳、咳．", 69, 1);
Talk("你的傷看上去很嚴重．", 0, 0);
Talk("咳、咳．恐怕我將不久于人世了．", 69, 1);
if HaveItemBool(53) then goto label28 end;
Talk("老前輩，你不會有事的．", 0, 0);
Talk("沒關系．老叫化死了又算什么呢．只是有一件憾事．．．", 69, 1);
Talk("什么事？看看我能不能幫你啊．", 0, 0);
Talk("我年輕的時候曾經在皇宮里吃過一道菜，叫”鴛鴦五珍燴”，可惜這輩子就吃過那一次，它的味道現在我還忘不了．．．", 69, 1);
Talk("那我去皇宮里抓幾個御廚回來給您做啊？", 0, 0);
Talk("不行啊．這做菜呢，不但要有手藝，還要講究器具．外邊的工具怎么能做出皇宮里的味道呢．", 69, 1);
if CheckSubMapPic(46, 6, 8252) then goto label63 end;
if InTeam(92) == false then goto label70 end;
Talk("洪老前輩，在下在宮里大小也有點實力，不如我送你進宮吃個夠啊．", 111, 0);
Talk("真的？那太好了．", 69, 1);
DarkScene();
ModifyEvent(-2, -2, 0, -2, 0, 0, 0, 0, 0, 0, 0, -2, -2);
AddMorality(3);
LightScene();
Talk("小寶，多謝你了．", 0, 0);
Talk("舉手之勞而已，大哥何必客氣呢．", 111, 0);
exit();
::label70::
Talk("我的朋友韋小寶在宮里是個大官，不如叫他幫忙啊．", 0, 0);
Talk("真的？那太好了．", 69, 1);
DarkScene();
ModifyEvent(-2, -2, 0, -2, 0, 0, 0, 0, 0, 0, 0, -2, -2);
AddMorality(3);
LightScene();
Talk("這就叫多個朋友多條路．", 0, 0);
exit();
::label63::
Talk("那這樣吧，我們偷偷潛入皇宮，去偷吃啊．", 0, 0);
Talk("咳、咳．我的傷恐怕不允許啊．", 69, 1);
Talk("我背你啊．", 0, 0);
Talk("那就多謝了．", 69, 1);
DarkScene();
ModifyEvent(-2, -2, 0, -2, 0, 0, 0, 0, 0, 0, 0, -2, -2);
ModifyEvent(46, 12, 0, -2, 0, 0, 818, 0, 0, 0, 0, -2, -2);
LightScene();
exit();
::label28::
Talk("前輩，其實你的傷因該沒什么大礙．", 0, 0);
Talk("你不用安慰我，我的傷我自己知道．", 69, 1);
Talk("不是啊，我這有本九陰真經里面記載了嚴重內傷的治法", 0, 0);
Talk("九陰真經怎么在你那了？我來看看．", 69, 1);
DarkScene();
LightScene();
Talk("照著經文里面的記載練真的感覺好多了．估計練個半年左右我的內傷就會好的．", 69, 1);
Talk("太好了．", 0, 0);
Talk("咦？那是什么？蛇！京城怎么會有蛇？", 69, 1);
if TryBattle(153) then goto label248 end;
Dead();
exit();
::label248::
LightScene();
Talk("京城怎么會有蛇？難道是歐陽鋒到了？", 69, 1);
Talk("那應該如何是好？", 0, 0);
Talk("別怕，我先教你一手專門對付蛇的．", 69, 1);
AddItem(45, 1);
AddItem(34, 10);
Talk("是誰殺了我的蛇？", 61, 0);
if TryBattle(154) then goto label288 end;
Dead();
exit();
::label288::
LightScene();
Talk("歐陽克都來了，看來老毒物不遠了．年輕人，我受傷無法對付他，我現在教你幾招打狗棒法，時間匆忙，你恐怕不能完全學會，但作作樣子應該能把西毒嚇跑．", 69, 1);
Talk("可是打狗棒法只能是丐幫幫主才能學啊．", 0, 0);
Talk("規矩雖然如此，但人命關天我現下只教你招式，不教你心法不就行了．", 69, 1);
DarkScene();
LightScene();
AddItem(101, 1);
Talk("老叫化，沒想到你竟然傷了我的侄兒．", 60, 0);
if TryBattle(155) == false then goto label327 end;
::label327::
LightScene();
Talk("＜這小子竟然會打狗棒法？＞哼！算你們厲害，克兒，我們走！", 60, 0);
DarkScene();
LightScene();
Talk("歐陽鋒雖然走了，但不會就這么罷休的，我看我們也快些走吧．", 69, 1);
DarkScene();
ModifyEvent(-2, -2, 0, -2, 0, 0, 0, 0, 0, 0, 0, -2, -2);
AddMorality(3);
OldSetScenePosition(21, 52);
LightScene();